version: '3.3'
services:
  midseaworkerdev:
    container_name: midseaWorkerDev
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app
      #- /usr/src/app/node_modules
    command: npm run development
