version: '3.3'
services:
  midseamysqlprod:
    container_name: midseaMysqlProd
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./docker/mysql_init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
      - ./scripts/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
